package com.example.tanklevelmonitor.utils

object Constants {

    const val PREFERENCES_APP_STATE = "PREFERENCES_APP_STATE"
    const val PREFERENCES_USER_INFO = "PREFERENCES_USER_INFO"
    const val PREFERENCES_SETTINGS = "PREFERENCES_SETTINGS"
    const val PREFERENCES_FIRST_TIME = "PREFERENCES_FIRST_TIME"
    const val PREFERENCES_TODAY_SWAP_COUNT = "PREFERENCES_TODAY_SWAP_COUNT"
    const val PREFERENCES_LAST_SAVED_DATE = "PREFERENCES_LAST_SAVED_DATE"

}